CONSTRUCT {
	?entity ?property ?value
} WHERE {
    ?component ifc:globalid ?sval .  
    ?sval rdf:value ?globalId . 
    BIND (URI(CONCAT("http://ifc-ld.org/ids#",?globalId) AS ?entity)) .
    ?component ?property ?value . 
} 